### ISSUE TITLE
Kode Warna Halaman Kategori Absensi

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/Presensi-Guru-2#35]
pas di kode warna kyknya baiknya cursor di olah jd default aja.
kalo yg ada kan krna class btn jadinya cursor pointer, pdhal itu kd bisa di klik.

kyp mamangs @syauqiahmd ?

### Foto Foto
> **Cursor pointer**
![image](https://user-images.githubusercontent.com/11961119/47059951-1b9d6b80-d1fe-11e8-8c02-eb4bfe67dfd2.png)

> **Cursor default**
![image](https://user-images.githubusercontent.com/11961119/47060020-5b645300-d1fe-11e8-90a0-e2dc3b3c39ad.png)

**Comment by syauqiahmd** [comment]
nah iyun... ku kelupaan semalam tuh meubah itunya... wkwk

**Comment by FaruqRahmadani** [comment]
Tp oke aja kah menurut pian?

**Comment by syauqiahmd** [comment]
ok banar...
![screen shot 2018-10-17 at 2 05 17 pm](https://user-images.githubusercontent.com/35471602/47065489-b5bcde00-d215-11e8-873f-9226887fefa7.png)
alternatif lain label warnanya model kaya ini

**Comment by FaruqRahmadani** [comment]
Kalo textnya di kasih border kyp? Apakah aneh?

**Comment by syauqiahmd** [comment]
aneh ruq.. sasak... tdi malam aku ada mencobai

**Comment by FaruqRahmadani** [comment]
Wokeh jd kyp baiknya lah. Klo yg putih tengah tu jd kurng terlihat wrnanya. Kena bngung hasilnya kyp.

**Comment by syauqiahmd** [comment]
iyun pang, bagus yg awal tdi ja lok kaya capsule

**Comment by FaruqRahmadani** [comment]
iyun pang asaku nah qi
