### ISSUE TITLE
Select2 tidak pakai scroller

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/Presensi-Guru-2#41]
### Bukti
![image](https://user-images.githubusercontent.com/11961119/47178058-aab89980-d34c-11e8-8abf-555ef72555a5.png)

### Terdapat pada
saat membuat issue ini ada di halaman tambah / edit data sekolah, yg ada di PR #39

### Apa yang harus dilakukan?
Belum riset, jadi belum tau apa

**Comment by syauqiahmd** [comment]
kena aing check lah, kayanya aing tau slahku dimna wkwkk

**Comment by FaruqRahmadani** [comment]
iyun qi, tp info itu ku td hnyr meolah fungsi di js, coba cek gin.
aku mikirnya dari pada meolah beberapa id sagan memanggil berkali2, baik sekalian ku olah class.

**Comment by syauqiahmd** [comment]
cek yg mana ruq ? kada ehem aing

**Comment by FaruqRahmadani** [comment]
di asset js yg _select2.js

**Comment by syauqiahmd** [comment]
okeh... wait

**Comment by syauqiahmd** [comment]
kdd seeder gasan kecamatan sama kelurahannya kah paman ?

**Comment by syauqiahmd** [comment]
![image](https://user-images.githubusercontent.com/35471602/47198904-76bb9380-d3a1-11e8-854f-196af389b164.png)
dapat bugnya, sekalinya kada kawa masih meumpati theme bs4, jdi errornya mun theme nya diganti gasan bs4, mun pake yg lain mau

ku styling beasa ae jdinya ini sekira sama

**Comment by syauqiahmd** [comment]
Nah pinanya bisa aja pang, malam aing bacai dlu kitabnya

Mun kda kawa jua, styling sorang ae sekira mirip wkwkw

**Comment by syauqiahmd** [comment]
Screen Recording 2018-10-20 at 12.35.59 AM
