### ISSUE TITLE
Error di NPM

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/Presensi-Guru-2#42]
### Bukti
![image](https://user-images.githubusercontent.com/11961119/47251784-450eff00-d46b-11e8-8dfd-9a3ebaba2ca8.png)

### Penjelasan
pas menjalankan `npm run watch` ada error, tapi tetap bisa jalan, entah warning atau apa.

**Comment by FaruqRahmadani** [comment]
wkwk, okeh masalah teratasi, kd kepikiran sampai kesana aing

**Comment by FaruqRahmadani** [comment]
ku close issuesnya, sudah rebes

**Comment by syauqiahmd** [comment]
Lupa aing ngasih comment kalo npi beasa wkwkwk
