### ISSUE TITLE
Penamaan Folder View

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/Presensi-Guru-2#44]
### Gambar
![image](https://user-images.githubusercontent.com/11961119/47251825-2bba8280-d46c-11e8-850e-39f37bc650f0.png)

### Penjelasan
Kayaknya bagusnya nama foldernya kd usah pakai prefix data. soalnya kena didalamnya (filenya) sudah menjelaskan masing2 bagiannya.
kyp mamangs?

**Comment by syauqiahmd** [comment]
Terserah aja pang paman... semalam tu ku bingung aja hahaha meumpati menu semalam je

**Comment by FaruqRahmadani** [comment]
kena kita olah PR beasa aja gin sagan membaiki ini, oke kah?

**Comment by syauqiahmd** [comment]
Wait wait... mun yg dataAdmin diubah jdi admin aja lok berati? Itu diatasnya ada folder admin

**Comment by FaruqRahmadani** [comment]
bedakan aja jadi ```admin``` lwn ```adminSekolah```

**Comment by FaruqRahmadani** [comment]
close kah? sdh di merge kalo?

**Comment by syauqiahmd** [comment]
iyun, closed
