### ISSUE TITLE
Tampilan Edit User Sendiri

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/Presensi-Guru-2#46]
minta tolong, olah akan tampilan sagan edit user sendiri sagan di menu *(liat pic)

### Guambar

> ![image](https://user-images.githubusercontent.com/11961119/47256318-c2109780-d4b0-11e8-9981-c8eed7518441.png)

**Comment by syauqiahmd** [comment]
wokeh... wait lah aing hndak anu dulu

**Comment by FaruqRahmadani** [comment]
ini santai aja qi, masih jauh wkwk

**Comment by syauqiahmd** [comment]
yuuun....
