### ISSUE TITLE
Variabel sass useless

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/Presensi-Guru-2#62]
### File : resources/assets/sass/_mentah/_variable.scss

> ![image](https://user-images.githubusercontent.com/11961119/47668324-1c150980-dbe3-11e8-99fe-4c64f975a68e.png)

### File :resources/assets/sass/_mentah/_login.scss

> ![image](https://user-images.githubusercontent.com/11961119/47668390-41a21300-dbe3-11e8-98a5-897c6c0034b3.png)

### Permasalahan
asaku sayang mun kita sdh declare variabel tp kd dipakai.

**Comment by syauqiahmd** [comment]
Oh iyun lah, wkwkwk blum aing asai wkwkwk

**Comment by FaruqRahmadani** [comment]
kyp jadinya qi? :v

**Comment by syauqiahmd** [comment]
Kena ku anui ruq

**Comment by syauqiahmd** [comment]
yg custum je ku asai ruq, mun yg dri bawaannya dibiarkan aja dulu
