### ISSUE TITLE
Responsive Table (Data Table)

### ISSUE THREAD

**Issue by faruq-rahmadani** [FaruqRahmadani/Presensi-Guru-2#77]
### Saat ini
![image](https://user-images.githubusercontent.com/11961119/48315408-c5f78b80-e610-11e8-8756-2d463c12f624.png)
Harusnya search dan data per page kada teumpat geser

### Solusi
sampai saat ini solusi yg ku tahu, hilangkan div class table-responsive, pindahkan ke table classnya. tp lewat jquery biar kada kena dom datatable.

**Comment by FaruqRahmadani** [comment]
dikerjakan di #78
