### ISSUE TITLE
warna pada chart donat

### ISSUE THREAD

**Issue by syauqiahmd** [FaruqRahmadani/Presensi-Guru-2#89]
isi chart donat berisikan statistik absensi yang sudah memiliki kode warna tersendiri di tiap kategorinya, jdi semestinya warna mengikuti warna tersebut bukan berdasarkan color scheme pada template website yg digunakan -___- mau kita baiki kada yo wkwkwkwk

**Comment by FaruqRahmadani** [comment]
rasanya ada ni ku tambahkan kyni qi, di data presensi tiap pegawai.
atau ada lg kah yg harus ditambahi kyni qi?

**Comment by syauqiahmd** [comment]
sudah ruq... aman dah
